# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'IMUIKitOCExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  #登录组件
  pod 'YXLogin', '1.1.0'

  #可选UI库
    pod 'NEContactUIKit', '9.7.0'
    pod 'NEConversationUIKit', '9.7.0'
    pod 'NEChatUIKit', '9.7.0'
    pod 'NETeamUIKit', '9.7.0'
    pod 'NEMapKit', '9.7.0'

    #基础kit库
    pod 'NECoreKit', '9.6.6'
    pod 'NECoreIMKit', '9.6.7'
    pod 'NECommonKit', '9.6.6'
    pod 'NECommonUIKit', '9.6.6'
    pod 'NEChatKit', '9.7.0'

  # 如果需要查看UI部分源码请注释掉以上在线依赖，打开下面的本地依赖
#    pod 'NEQChatUIKit', :path => '../NEQChatUIKit/NEQChatUIKit.podspec'
#    pod 'NEContactUIKit', :path => '../NEContactUIKit/NEContactUIKit.podspec'
#    pod 'NEConversationUIKit', :path => '../NEConversationUIKit/NEConversationUIKit.podspec'
#    pod 'NETeamUIKit', :path => '../NETeamUIKit/NETeamUIKit.podspec'
#    pod 'NEChatUIKit', :path => '../NEChatUIKit/NEChatUIKit.podspec'

end


