platform :ios, '8.0'
workspace 'NIM.xcworkspace'


target 'NIM' do
        project 'NIM.xcodeproj'
        pod 'FMDB', '~> 2.5'
        pod 'Reachability', '~> 3.1.1'
        pod 'CocoaLumberjack', '~> 2.0.0-rc2'
        pod 'SSZipArchive', '~> 1.2'
        pod 'NIMKit/Full', :path => '../'
end
