platform :ios, '8.0'
workspace 'NIM.xcworkspace'


target 'NIM' do
        project 'NIM.xcodeproj'
        pod 'FMDB', '~> 2.5'
        pod 'Reachability', '~> 3.1.1'
        pod 'CocoaLumberjack', '~> 2.0.0-rc2'
        pod 'SSZipArchive', '~> 1.2'
        pod 'SDWebImage', '3.8.2'
        pod 'Toast', '~> 3.0'
        pod 'SVProgressHUD', '~> 2.0.3'
        pod 'M80AttributedLabel', '~> 1.5.0'
        pod 'CTAssetsPickerController', '~> 3.3.2-alpha'
        pod 'NIMKit/Lite'
end
